package rofex

const (
	pathAuth          = "auth/getToken"
	pathSegments      = "rest/segment/all"
	pathInstrAll      = "rest/instruments/all"
	pathInstrDetails  = "rest/instruments/details"
	pathInstrDetail   = "rest/instruments/detail"
	pathInstrByCFI    = "rest/instruments/byCFICode"
	pathInstrBySeg    = "rest/instruments/bySegment"
	pathMDGet         = "rest/marketdata/get"
	pathTrades        = "rest/data/getTrades"
	pathOrderStatus   = "rest/order/id"
	pathOrderAllByID  = "rest/order/allById"
	pathOrderByOrder  = "rest/order/byOrderId"
	pathOrderByExecID = "rest/order/byExecId"
	pathOrderFilleds  = "rest/order/filleds"
	pathOrderActives  = "rest/order/actives"
	pathOrderReplace  = "rest/order/replaceById"
	pathNewOrder      = "rest/order/newSingleOrder"
	pathCancelOrder   = "rest/order/cancelById"
	pathAllOrders     = "rest/order/all"
	pathAccounts      = "rest/accounts"
	pathAccountPos    = "rest/risk/position/getPositions"
	pathDetailedPos   = "rest/risk/detailedPosition"
	pathAccountReport = "rest/risk/accountReport"
)
