name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Go mod tidy
        run: |
          go mod tidy -v

      - name: Format (gofmt -s)
        run: |
          fmt_out=$(gofmt -s -l .)
          if [ -n "$fmt_out" ]; then
            echo "Files not formatted:" && echo "$fmt_out" && exit 1
          fi

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -v ./...
